dist: trusty
language: python
python:
  - "3.7"

cache: pip


addons:
postgresql: "10"

install:
  - pip install -r requirements.txt --quiet
  - pip install codecov


before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py test
  - coverage run --source=news manage.py test news

after_success:
  - codecov
